version: '3'

services:
  app:
    build: .
    volumes:
      - .:/go/src/

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    extra_hosts:
      - "host.docker.internal:172.17.8.1"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAKFA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER: INTERNAL://:9092,OUTSIDE://:9094
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INFER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
    extra_hosts:
      - "host.docker.internal:172.17.8.1"
