apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: mx-payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      hostname: kafka
      hostAliases:
        - ip: "172.17.0.1"
          hostnames:
          - "host.docker.internal"
      initContainers:
        - name: init-zookeeper
          image: busybox:1.28
          command:
            - sh
            - -c
            - >
              until nslookup zookeeper; do
                echo "waiting for zookeeper";
                sleep 2;
              done
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            - name: KAFKA_LISTENERS
              value: "INTERNAL://:9092,EXTERNAL://:9094"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INTERNAL://kafka:9092,EXTERNAL://host.docker.internal:9094"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
            # this is a workaround to prevent using a deprecated configuration
            - name: KAFKA_PORT 
              value: ""
            # Uncomment the following lines to enable debug logging
            # - name: LOG4J_LOGGER_KAFKA
            #   value: "DEBUG"
