apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: mx-payments
spec:
  selector:
    app: kafka
  ports:
    - name: internal
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: external
      protocol: TCP
      port: 9094
      targetPort: 9094