FROM golang:1.18

WORKDIR /go/src

COPY . .

RUN apt-get update && \
  apt-get install -y --no-install-recommends gcc git libssl-dev g++ make && \
  cd /tmp && git clone https://github.com/edenhill/librdkafka && \
  cd librdkafka && git checkout tags/v2.0.2 && \
  ./configure && make && make install && \
  ldconfig &&\
  cd ../ && rm -rf librdkafka

RUN go build -o /go/bin/mx-payments cmd/main.go 

CMD ["/go/bin/mx-payments"]