apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # base64 encoded username
  POSTGRES_PASSWORD: c3VwZXJzZWNyZXQ=  # base64 encoded password
