AWSTemplateFormatVersion: 2010-09-09
Description: Basic infrastructure to support Terraform
Resources:
  TerraformStateBucket:
    DeletionPolicy: Retain
    Type: 'AWS::S3::Bucket'
    Description: Bucket that stores Terraform state files
    Properties:
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled

  TerraformStateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "LockID"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "LockID"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST

Outputs:
  S3Bucket:
    Description: Bucket that stores Terraform state files
    Value: !Ref S3Bucket