// Code generated by MockGen. DO NOT EDIT.
// Source: adapter/broker/interface.go

// Package mock_broker is a generated GoMock package.
package mock_broker

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockProducer is a mock of Producer interface.
type MockProducer[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockProducerMockRecorder[T]
}

// MockProducerMockRecorder is the mock recorder for MockProducer.
type MockProducerMockRecorder[T any] struct {
	mock *MockProducer[T]
}

// NewMockProducer creates a new mock instance.
func NewMockProducer[T any](ctrl *gomock.Controller) *MockProducer[T] {
	mock := &MockProducer[T]{ctrl: ctrl}
	mock.recorder = &MockProducerMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProducer[T]) EXPECT() *MockProducerMockRecorder[T] {
	return m.recorder
}

// Publish mocks base method.
func (m *MockProducer[T]) Publish(message T, key []byte, topic string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", message, key, topic)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockProducerMockRecorder[T]) Publish(message, key, topic interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockProducer[T])(nil).Publish), message, key, topic)
}
